// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int runs = Integer.parseInt(args[0]);
		int overHalf = 0;
		int underHalf = 0;
		for (int i = 0; i < runs; i++) {
			double r = Math.random();
			if (r > 0.5) {
				overHalf++;
			} else {
				underHalf++;
			}
		}
		if (underHalf != 0) {
			double result = (double) overHalf / (double) underHalf;
			System.out.println("Ratio: " + result);
		}
	}
}
